<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE included
[
 <!ELEMENT included ( iso:p )* >
 <!ELEMENT iso:p  (#PCDATA) >
 
 <!ATTLIST included
    xmlns:iso 	CDATA #IMPLIED
	xmlns:nvdl CDATA #IMPLIED
	xmlns:xhtml CDATA #IMPLIED
	xmlns:schold	CDATA #IMPLIED
	xmlns:crdl CDATA #IMPLIED
	xmlns:xi CDATA #IMPLIED
	xmlns:dtll CDATA #IMPLIED
	xmlns:dsdl CDATA #IMPLIED
	xmlns:relax CDATA #IMPLIED
	>
  <!ATTLIST iso:p
    xml:id  CDATA #IMPLIED
    id		CDATA #IMPLIED
    nickname ID		#IMPLIED
    >
]>
<included
    xmlns:iso="http://purl.oclc.org/dsdl/schematron" 
    xmlns:nvdl="http://purl.oclc.org/dsdl/nvdl" 
	xmlns:xhtml="http://www.w3.org/1999/xhtml"
    xmlns:schold="http://www.ascc.net/xml/schematron"
    xmlns:crdl="http://purl.oclc.org/dsdl/crepdl/ns/structure/1.0"
    xmlns:xi="http://www.w3.org/2001/XInclude"
    xmlns:dtll="http://www.jenitennison.com/datatypes"
    xmlns:dsdl="http://www.dsdl.org/namespace" 
    xmlns:relax="http://relaxng.org/ns/structure/1.0">
    
    <iso:p  xml:id="id1">First <iso:span> text</iso:span></iso:p>
    
     <iso:p xml:id="id2">Second and third text</iso:p> 
     
     <iso:p id="id3">Second and third text</iso:p> 
     
     <iso:p nickname="id4">Fourth text</iso:p>
    
 </included>